<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="fb_LocalTime" Id="{4d26523e-7cf5-060f-2676-dd94d0395994}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_LocalTime
VAR_INPUT

END_VAR
VAR_OUTPUT
  sLocalTime  : STRING;
  dtLocalTime : DT;
END_VAR
VAR
  GetSysTime    : FW_GetSystemTime;
  strFileTime   : Tc2_Utilities.T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GetSysTime(dwTimeLo=> strFileTime.dwLowDateTime, dwTimeHi=> strFileTime.dwHighDateTime);

sLocalTime := SYSTEMTIME_TO_STRING( FILETIME_TO_SYSTEMTIME( strFileTime ) );
dtLocalTime := systemtime_to_dt( FILETIME_TO_SYSTEMTIME( strFileTime ) );


]]></ST>
    </Implementation>
    <LineIds Name="fb_LocalTime">
      <LineId Id="13" Count="1" />
      <LineId Id="19" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>